### ISSUE TITLE
Provision error

### ISSUE THREAD

**Issue by Saphyel** [geerlingguy/drupal-dev-vm#25]
failed: [drupaldev] => {"changed": true, "cmd": ["drush", "make", "-y", "/vagrant/drupal.make.yml", "/var/www/drupal"], "delta": "0:00:32.571113", "end": "2015-01-10 21:24:00.839312", "rc": 1, "start": "2015-01-10 21:23:28.268199"}
stderr: Beginning to build /vagrant/drupal.make.yml.                         [ok]
drupal-8.0.x-dev downloaded.                                         [ok]
File devel-8.x-1.x-dev.tar.gz_date=1420592880 is corrupt (wrong md5  [error]
checksum).

FATAL: all hosts have already failed -- aborting
drupaldev                  : ok=88   changed=2    unreachable=0    failed=1

**Comment by geerlingguy** [comment]
Every now and then I get the same error; it seems to happen when the latest development release has been packaged, but Drupal.org's packaging script has not completed updating all the MD5 hashes.

To resolve the issue, you can explicitly set the drush version and tell it to update in your config.yml, like:

    drush_version: 6.5.0
    drush_keep_updated: yes
