### ISSUE TITLE
Should drupal.make.yml be a configuration file as well?

### ISSUE THREAD

**Issue by wizonesolutions** [geerlingguy/drupal-dev-vm#26]
I notice that to get Drupal 7 or 6, `drupal.make.yml` has to be changed, but it's not in `.gitignore`, hence the repo gets dirty and the config can't be as easily updated when there are changes.

Should this be done up like `config.yml`?

I'm using D8, just noticed this and thought to ask.

**Comment by geerlingguy** [comment]
Yes. Most definitely, and I don't know why I didn't think of this sooner... the example should just contain a barebones example of how to do things with the latest version of Drupal (e.g. Drupal 8), and you should copy it to `drupal.make.yml`.
