### ISSUE TITLE
vagrant up error

### ISSUE THREAD

**Issue by matoeilD** [geerlingguy/drupal-dev-vm#29]
vm:
* The host path of the shared folder is missing: ~/Sites/drupal

**Comment by geerlingguy** [comment]
In your `config.yml`, you will need to set a valid local path to share a folder into the virtual machine, or set the value to `[]` if you don't want to share any local folders with the VM (e.g. `vagrant_synced_folders: []`).

The local path must exist if you want to sync the path with the VM.
