### ISSUE TITLE
Memcached support

### ISSUE THREAD

**Issue by sndpl** [geerlingguy/drupal-dev-vm#34]
By default memcached support is enabled in the config.yml, but to make this work I had to add the following lines to the requirements.txt:

```
geerlingguy.memcached
geerlingguy.php-memcached
```

Is this correct? or did i miss something else?

**Comment by prics** [comment]
I had the same problem and did the same fix.

**Comment by geerlingguy** [comment]
Thanks for catching this! I've fixed it in the latest commit.
