### ISSUE TITLE
Drupal 6 + Drush 6 support

### ISSUE THREAD

**Issue by mchelen** [geerlingguy/drupal-dev-vm#38]
Hi, everything seems to work fine with D8 and D7, but I run into errors when installing D6.

It seems that at some point the `/var/www/drupal` directory is not being created.

This is the last part of the Ansible output:
```
TASK: [Remove default virtualhost file.] ************************************** 
changed: [drupaldev]

TASK: [Check if Drupal is already set up.] ************************************ 
ok: [drupaldev]

TASK: [Generate Drupal site with drush makefile.] ***************************** 
changed: [drupaldev]

TASK: [Install Drupal (standard profile) with drush.] ************************* 
failed: [drupaldev] => {"failed": true, "rc": 258}
msg: cannot change to directory '/var/www/drupal': path does not exist

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/mikechelen/playbook.retry

drupaldev                  : ok=121  changed=56   unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

These are the relevant lines from:
`config.yml`:
```
drupal_major_version: 6
drush_version: master
```
Also tried `drush_version: 6.x`

`drupal.make.yml`:
```
core: 6.x

projects:

  drupal:
    type: core
    version: 6.x

  devel: 1.x
```
Also tried with `core: 6.34` and `version: 6.34`

**Comment by mchelen** [comment]
I did some more checking and noticed there are actually different errors depending on the version of Drush.
The error about `/var/www/drupal` not being created occurs with `drush_version: 6.x`. I tried running this command manually:
```
drush make -y /vagrant/drupal.make.yml /var/www/drupal/
```
The weird thing is it does not create `/var/www/drupal` nor does it show any errors.
`drush --version` shoes `6.6-dev`

**Comment by mchelen** [comment]
It looks like the problem is that Drush 6.x cannot read the YAML formatted make file. It works fine if I change the makefile to this format:

```
api = 2
core = 6.x
projects[drupal][version] = 6.x
```

I checked the Drush 6.x docs and don't see the other makefile format mentioned: https://github.com/drush-ops/drush/blob/6.x/docs/make.txt

**Comment by mchelen** [comment]
The other issue is that for Drush 7 the basic install profile is named `standard` whereas in Drush 6 the install profile is called `default`.

**Comment by geerlingguy** [comment]
@mchelen - Thanks for the tips! I didn't get around to working on this today, but I've documented your fixes in the README.md file, under the heading "Drupal 6 Notes". Please let me know if that's adequate, or if you find any other interesting fixes you need to apply.

Thanks!

**Comment by mchelen** [comment]
@geerlingguy Yup I think that covers it, with those 2 modifications it seems to be working now. If I get a chance I'll add some logic to change the commands based on the selected Drush version.

Thanks!

For reference, here is the error that shows up when trying to install `standard` profile using Drush 6
```
TASK: [Install Drupal (standard profile) with drush.] ************************* 
<127.0.0.1> --account-pass=admin --site-name=Drupal Test Site --account-name=admin --db-url=mysql://root:********@localhost/drupal chdir=/var/www/drupal
failed: [drupaldev] => {"changed": true, "cmd": ["drush", "si", "standard", "-y", "--site-name=Drupal Test Site", "--account-name=admin", "--account-pass=admin", "--db-url=mysql://root:root@localhost/drupal"], "delta": "0:00:01.359208", "end": "2015-03-01 22:16:28.795022", "rc": 1, "start": "2015-03-01 22:16:27.435814", "warnings": []}
stderr: Starting Drupal installation. This takes a few seconds ...           [ok]
Table &#039;drupal.variable&#039; doesn&#039;t exist                 [warning]
query: SELECT value FROM variable WHERE name =
&#039;install_task&#039; database.mysql.inc:135
Table &#039;drupal.variable&#039; doesn&#039;t exist                 [warning]
query: SELECT value FROM variable WHERE name =
&#039;install_task&#039; database.mysql.inc:135
The site install task '' failed.                                     [error]
```
