### ISSUE TITLE
Set up Drupal in a synced folder for easier development

### ISSUE THREAD

**Issue by prics** [geerlingguy/drupal-dev-vm#41]
I have a little problem and can't seem to find a solution for it: I want the project to be in the synch folder.
I've tried to set /var/www/drupal in the VM to be the synch folder instead of /drupal, but when the VM boots, the folder is synched with the local one which is empty, so no more drupal installation.
Is there any way to achieve this ?

**Comment by geerlingguy** [comment]
I just ran into the same exact issue at a Drupal sprint at #MidCamp, so this is a problem I'd like to solve. Taking a look now.
