### ISSUE TITLE
Get username from config variable

### ISSUE THREAD

**Issue by mchelen** [geerlingguy/drupal-dev-vm#43]
There is a hardcode username of `vagrant` in some of the `provisioning/tasks/' files. It would be nice to set a variable in the config and then use that instead, in case someone wants to set a different username.

https://github.com/geerlingguy/drupal-dev-vm/blob/master/provisioning/tasks/www.yml#L9
https://github.com/geerlingguy/drupal-dev-vm/blob/master/provisioning/tasks/www.yml#L15
https://github.com/geerlingguy/drupal-dev-vm/blob/master/provisioning/tasks/drupal.yml#L59

**Comment by geerlingguy** [comment]
Makes perfect sense!

**Comment by mchelen** [comment]
Awesome, thanks!
